name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
    - uses: actions/checkout@v2
    - name: Build the API Docker image
      id: docker_build_push_api
      uses: docker/build-push-action@v2
      with:
        repository: bwouters/findr-api
        tag_with_ref: true
        context: Brixel.Findr.API
        file: Brixel.Findr.API/Dockerfile
        push: true
        tags: bwouters/findr-api:latest
    - name: Image digest
      run: echo ${{ steps.docker_build_push_api.outputs.digest }}
        
    - name: Build the Angular Docker image
      id: docker_build_push_angular
      uses: docker/build-push-action@v2
      with:
        repository: bwouters/findr-angular
        tag_with_ref: true
        context: Brixel.Findr.Angular/brixel-findr
        file: Brixel.Findr.Angular/brixel-findr/Dockerfile
        push: true
        tags: bwouters/findr-angular:latest
    - name: Image digest
      run: echo ${{ steps.docker_build_push_angular.outputs.digest }}
