name: .NET Core Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      working-directory: 'Brixel.Findr.API'
      run: dotnet restore  .\Brixel.Findr.API.csproj
    - name: Build      
      working-directory: 'Brixel.Findr.API'
      run: dotnet build .\Brixel.Findr.API.csproj  --configuration Release --no-restore
    - name: Test
      working-directory: 'Brixel.Findr.API'
      run: dotnet test  .\Brixel.Findr.API.csproj --no-restore --verbosity normal
